server:
  port: 8763
  
eureka:
  client:
    register-with-eureka: false # 不要注册自己，以server方式运行 
    fetch-registry: false
    serviceUrl:
      defaultZone: http://peer1.example.com:8762/eureka
  instance:
    hostname: peer2.example.com