server:
  port: 8761
  display-name: eurake-server1
  context-path: /eurake-server1
  
eureka:
  client:
    register-with-eureka: false # 不要注册自己，以server方式运行 
    fetch-registry: false
    serviceUrl:
      defaultZone: http://peer2.example.com:8762/eurake-server2
  instance:
    hostname: peer1.example.com