
server:
  port: 9999
  
logging:
  level:
    root: INFO
    io.junq: DEBUG 

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emall?characterEncoding=utf8&useSSL=true
    username: fly
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: spring-boot
