server:
  port: 9999
  
logging:
  level:
    root: INFO
    io.junq: DEBUG 

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emall
    username: emall
    password: emallPwd
    driver-class-name: com.mysql.jdbc.Driver
