server:
  port: 8762
  display-name: eurake-server2
  context-path: /eurake-server2

  
eureka:
  client:
    register-with-eureka: false # 不要注册自己，以server方式运行 
    fetch-registry: false
    serviceUrl:
      defaultZone: http://peer1.example.com:8761/eurake-server1
  instance:
    hostname: peer2.example.com