CREATE TABLE `cart` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `customer_id` VARCHAR(128) NOT NULL,
  `items` TEXT NULL,
  `created_at` DATETIME AS CURRENT_TIMESTAMP,
  `changed_at` DATETIME AS CURRENT_TIMESTAMP
 );