server:
  port: 9903
  
logging:
  level:
    root: INFO
    io.junq: DEBUG 

management:
  port: 9902
  context-path: /manage
  security:
    enabled: false

spring:
  application:
    name: order-service
    instance_id: 001
  cloud:
    inetutils:
      preferred-networks:
        - 192.168
        - 10.0
  datasource:
    url: jdbc:mysql://localhost:3306/emall
    username: emall
    password: emallPwd
    driver-class-name: com.mysql.jdbc.Driver
