-- MySQL Script generated by MySQL Workbench
-- Tue Mar 14 22:41:13 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema emall
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema emall
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `emall` DEFAULT CHARACTER SET utf8 ;
USE `emall` ;


-- -----------------------------------------------------
-- Table `emall`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emall`.`order` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(64) NOT NULL,
  `products` VARCHAR(1024) NOT NULL,
  `amount` INT(11) UNSIGNED NOT NULL,
  `status` SMALLINT(6) NOT NULL,
  `payment_type` VARCHAR(45) NULL,
  `note` VARCHAR(128) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `changed_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_user_id` (`user_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
