version: '2'

services:
  account-db:
    image: mysql/mysql-server:5.7
    volumes:
      - db_data:/var/lib/mysql
    hostname: account-db
    restart: always
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: account0bP@ssw0rd
      MYSQL_DATABASE: emall
      MYSQL_USER: emall
      MYSQL_PASSWORD: emallPwd
  account-service:
    build: 
      context: .
      dockerfile: Dockerfile
    image: stuq-1160-emall/account-service
    depends_on:
      - account-db
    links:
      - account-db
    hostname: account
    restart: always
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    ports:
      - "29999:9999"
      - "29998:9998"
    environment:
      CONSUL_HOST: localhost
      CONSUL_PORT: 8500
volumes:
    db_data: