server:
  port: 8080

logging:
  level:
    root: INFO
    io.junq: DEBUG 

management:
  port: 8079
  context-path: /manage
  security:
    enabled: false

spring:
  application:
    name: emall-gateway
    instance_id: 001
  cloud:
    inetutils:
      preferred-networks:
        - 192.168
        - 10.0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    appGroupName: emall
    instanceId: ${spring.application.name}:${spring.application.instance_id}:${random.value}
   
zuul:
  ignoredServices: '*'
  routes:  
    orders:
      service-id: order-service
      path: /v1/orders/**
      stripPrefix: false
    users:
      service-id: account-service
      path: /v1/users/**
      stripPrefix: false
    products:
      service-id: product-service
      path: /v1/products/**
      stripPrefix: false
