server:
  port: 9999
  
logging:
  level:
    root: INFO
    io.junq: DEBUG 

management:
  port: 9998
  context-path: /manage
  security:
    enabled: false

spring:
  application:
    name: account-service
    instance_id: 001
  cloud:
    inetutils:
      preferred-networks:
        - 192.168
        - 10.0
  datasource:
       url: jdbc:mysql://localhost:3306/emall?characterEncoding=utf8&useSSL=true
       username: fly
       password: 123456
       driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    healthcheck:
      enabled: true
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    appGroupName: emall
    instanceId: ${spring.application.name}:${spring.application.instance_id}:${random.value}

    
    