server:
  port: 9905
  tomcat:
    accesslog:
      enabled: true
      directory: logs
      pattern: '%h %l %u %t "%r" %s %b %Dms'
      buffered: false
  
logging:
  level:
    root: INFO
    io.junq: DEBUG 
    org.springframework.security: DEBUG

management:
  port: 9904
  context-path: /manage
  security:
    enabled: false

spring:
  application:
    name: cart-service
    instance_id: 001
  cloud:
    inetutils:
      preferred-networks:
        - 192.168
        - 10.0
    consul:
      host: ${CONSUL_HOST}
      port: ${CONSUL_PORT}
      discovery:
        enable: true 
        instanceId: ${spring.application.name}:${spring.application.instance_id}:${random.value} # 实例ID
        healthCheckPath: ${management.context-path}/health # 健康检测路径
        healthCheckInterval: 15s # 健康检测时间间隔
        tags: emall # 服务的标签
  datasource:
    url: jdbc:mysql://cart-db/emall?autoReconnect=true&useSSL=false
    username: emall
    password: emallPwd
    driver-class-name: com.mysql.jdbc.Driver
    schema: file:/emall/data/schema-mysql.sql
    initialize: true
    continue-on-error: false
    
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      defaultZone: ${EUREKA_URI}
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    appGroupName: emall
    instanceId: ${spring.application.name}:${spring.application.instance_id}:${random.value}
