server:
  port: 9905
  tomcat:
    accesslog:
      enabled: true
      directory: logs
      pattern: '%h %l %u %t "%r" %s %b %Dms'
      buffered: false
  
logging:
  level:
    root: INFO
    io.junq: DEBUG 
    org.springframework.security: DEBUG

management:
  port: 9904
  context-path: /manage
  security:
    enabled: false

spring:
  application:
    name: cart-service
    instance_id: 001
  cloud:
    inetutils:
      preferred-networks:
        - 192.168
        - 10.0
    consul:
      host: localhost
      port: 18500
      discovery:
        enable: true 
        instanceId: ${spring.application.name}:${spring.application.instance_id}:${random.value} # 实例ID
        healthCheckPath: ${management.context-path}/health # 健康检测路径
        healthCheckInterval: 15s # 健康检测时间间隔
        tags: emall # 服务的标签
  datasource:
    url: jdbc:mysql://localhost:3306/emall
    username: emall
    password: emallPwd
    driver-class-name: com.mysql.jdbc.Driver
    schema: file:data/schema-mysql.sql
    initialize: true
    continue-on-error: false