version: '2'

services:
  cart-db:
    image: mysql/mysql-server:5.7
    volumes:
      - db_data:/var/lib/mysql
    hostname: cart-db
    restart: always
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: cart0bP@ssw0rd
      MYSQL_DATABASE: emall
      MYSQL_USER: emall
      MYSQL_PASSWORD: emallPwd
  cart-service:
    build: 
      context: .
      dockerfile: Dockerfile
    image: stuq-1160-emall/cart-service
    depends_on:
      - cart-db
    links:
      - cart-db
    hostname: cart
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    ports:
      - "29905:9905"
      - "29904:9904"
volumes:
    db_data: